apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git::https://github.com/jayanth-tjvrr/arlon-bc//bc1?ref=temp
configurations:
- configurations.yaml
patchesStrategicMerge:
- patch.yaml
