apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git::https://github.com/jayanth-tjvrr/arlon-bc//bc1
configurations:
- configurations.yaml
patches:
- path: patch.yaml
- path: patch1.yaml
- path: patch2.yaml
