apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- git::https://github.com/jayanth-tjvrr/arlon-bc?ref=main//bc1
configurations:
- configurations.yaml
patches:
- target:
    group: cluster.x-k8s.io
    version: v1beta1
    kind: MachineDeployment
  path: patch.yaml
- target:
    group: controlplane.cluster.x-k8s.io
    version: v1beta1
    kind: AWSManagedControlPlane
  path: patch1.yaml
- target:
    group: infrastructure.cluster.x-k8s.io
    version: v1beta1
    kind: AWSMachineTemplate
  path: patch2.yaml
